apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: catdog-db-credentials
  namespace: catdog-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: catdog-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: catdog-platform/database-credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: catdog-platform/database-credentials
        property: password
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: catdog-platform/database-credentials
        property: password
