{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cat-dog-voting.fullname" . }}-backend-pdb
  labels:
    {{- include "cat-dog-voting.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: catdog-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cat-dog-voting.fullname" . }}-frontend-pdb
  labels:
    {{- include "cat-dog-voting.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: catdog-frontend
{{- end }}
