apiVersion: v1
kind: Secret
metadata:
  name: catdog-db-secret
  namespace: catdog-platform
  labels:
    app.kubernetes.io/name: catdog-db-secret
    app.kubernetes.io/part-of: catdog-voting
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "ProductionSecurePassword123!"
  POSTGRES_PASSWORD: "ProductionSecurePassword123!"
