apiVersion: v1
kind: ServiceAccount
metadata:
  name: catdog-sa
  namespace: catdog-platform
  labels:
    app.kubernetes.io/name: catdog-sa
    app.kubernetes.io/part-of: catdog-voting
automountServiceAccountToken: false
