apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cat-dog-voting-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: catdog-platform-project
  source:
    repoURL: 'https://github.com/METEORBUZZ/PRODUCTION-KUBERNETES-PLATFORM.git'
    targetRevision: main
    path: helm/cat-dog-voting
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: catdog-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
