apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: catdog-platform-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Production Kubernetes Platform GitOps Project
  sourceRepos:
    - '*'
  destinations:
    - namespace: catdog-platform
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
